name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.11
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached virtual environment
      id: cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install --no-ansi --no-interaction
    - name: Test with pytest
      run: poetry run pytest -vv --cov=app --cov-report=term-missing --cov-report=xml tests
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        COMMIT_SHA: $GITHUB_SHA
        BRANCH_NAME: ${GITHUB_REF#refs/heads/}
    - name: Push coverage report to CodeClimate
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: 75fa0e5f1732473ae15cbfd2cd58e9c109990133038e68565f72ddbb87f0ec1c
      with:
        coverageCommand: true
