name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      uses: snok/install-poetry@v1.1.6
    - name: Install Python Dependencies
      run: poetry install --no-ansi --no-interaction
    - name: Test with pytest
      run: poetry run pytest --cov=app --cov-report=term-missing --cov-report=xml tests
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        COMMIT_SHA: $GITHUB_SHA
        BRANCH_NAME: ${GITHUB_REF#refs/heads/}
    - name: Push Coverage Report to CodeClimate
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: 75fa0e5f1732473ae15cbfd2cd58e9c109990133038e68565f72ddbb87f0ec1c
      with:
        coverageCommand: true
